services:
  - type: web
    name: app-requisiciones-vendedores
    env: node
    region: oregon
    buildCommand: cd frontend && npm install && npm run build && cd ../backend && npm install
    startCommand: cd backend && node server.js
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: requisiciones-db
          property: connectionString

databases:
  - name: requisiciones-db
    region: oregon
    plan: free
